version = 1

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = ["angular"]
  environment = [
    "browser",
    "jasmine"
  ]
  style_guide = "airbnb"
  dialect = "typescript"